"""
Django settings for misitio project.

Generated by 'django-admin startproject' using Django 1.11.4.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#contraseña que se va a usar para conectar a la base de datos
SECRET_KEY = '@v3ic7t#we3kw!=br6!s#jc9sgo=a=47#p6c4=ps+l%&d&60s$'

# SECURITY WARNING: don't run with debug turned on in production!
#nos permite ver los errores que se tendran en la pagina al finalizar se debe pcultare
DEBUG = True
#se define quienes se puden conectar
ALLOWED_HOSTS = []


# Application definition
#son todos los modulos del programa
INSTALLED_APPS = [
#permite administrar toda la aplicacion permisos de usuario , etc
    'django.contrib.admin',
    #nos permite realizar la autenticacion
    'django.contrib.auth',
    'django.contrib.contenttypes',
    #apliacion para el manejo de sesiones
    'django.contrib.sessions',
    #modulo de mensajes
    'django.contrib.messages',
    #despliegue de logos e imagines estaticos
    'django.contrib.staticfiles',
    'bolg',
]

MIDDLEWARE = [#apliaciones intermedias en dos parttes del programa para manej
#ar todo lo refente a la autenticacion
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'misitio.urls'#cual es la primera pagina a la que buscara las direcciones

TEMPLATES = [#plantillas que ya trae para trastearla
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'misitio.wsgi.application'#el que se comuica con el servidor web


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {#se define cual es la base de datos usar
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [#validaciones para los password donde se restrin todos los pasword
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'es-gt'

TIME_ZONE = 'America/Guatemala'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
